---
title: "sfcrime"
author: "Kent Mok"
date: "January 13, 2016"
output: html_document
---

#Load data
```{r load_data}
system.time(trainraw <- read.csv("Data/sfcrime.csv"))

system.time(trainraw <- readRDS("Data/test.RDS"))


# Load packages
Installed <- require("plyr")
if (!Installed) {
    install.packages("plyr")
    library("plyr")
}

Installed <- require("ggplot2")
if (!Installed) {
    install.packages("ggplot2")
    library("ggplot2")
}

Installed <- require("scales")
if (!Installed) {
    install.packages("scales")
    library("scales")
}

Installed <- require("data.table")
if (!Installed) {
    install.packages("data.table", repos = "http://cran.rstudio.com")
    library("data.table")
}

Installed <- require("bit64")
if (!Installed) {
    install.packages("bit64", repos = "http://cran.rstudio.com")
    library("bit64")
}

system.time(trainraw <- fread("Data/sfcrime.csv", sep = ',', showProgress=F))
```

#Exploratory Data Analysis

```{r}
summary(trainraw)
str(trainraw)
unique(trainraw$Category)
```

#Clean Data
```{r}
# Convert Date variable from factor to date
trainraw$Date <- as.Date(trainraw$Date, format = "%m/%d/%Y")
# Count daily frequency of each crime
freqByCategory <- count(trainraw, c("Date", "Category"))

# Create data frame with only data from Category of ARSON
dataByArson <- freqByCategory[freqByCategory$Category == "ARSON", c(1, 3)]
# Extract month and year into new variables
dataByArson$Month <- as.Date(cut(dataByArson$Date, breaks = "month"))
dataByArson$Year <- as.Date(cut(dataByArson$Date, breaks = "year"))

# Plot by month
plotByMonth <- ggplot(data = dataByArson, aes(Month, freq))
plotByMonth <- plotByMonth +
    stat_summary(fun.y = sum,  # adds up all observations for the month
                 geom = "line") +
    scale_x_date(labels = date_format("%m/%Y")) +  # custom x-axis labels
    ggtitle("Arson by Month") +
    labs(x = "Time", y = "Occurences per Month") +
    theme_bw()
print(plotByMonth)

# Plot by year
plotByYear <- ggplot(data = dataByArson, aes(Year, freq))
plotByYear <- plotByYear +
    stat_summary(fun.y = sum,  # adds up all observations for the month
    geom = "line")
plotByYear <- plotByYear +
    scale_x_date(labels = date_format("%Y"))  # custom x-axis labels
plotByYear <- plotByYear + ggtitle("Arson by Year")
print(plotByYear)

```
