---
title       : SF Crime History App
subtitle    : 
author      : Kent Mok
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : standalone # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

This app explores the history of crime in San Francisco by category. It plots  
the occurrences by week or by year of a chosen crime category. The data is for  
San Francisco crime between January 1, 2003 and January 13, 2016. 

The data can be found at:  
https://data.sfgov.org/Public-Safety/SFPD-Incidents-from-1-January-2003/tmnf-yvry

The project can be found at:  
https://kmok23.shinyapps.io/CrimeApp/

The project Github repository can be found at:  
https://github.com/kmok23/CrimeApp


--- .class #id 

## Features

The app loads the data and then displays the user controls as well as the
plot for the default crime category.

* Plot frequency of a type of crime over time
* User can switch the type of crime from a drop down menu
* User can switch the breaks in time between "months" and "years"
* Plot will update automatically

--- .class #id 

## Sample Plot

The plot below is a sample of the plot with Arson as the selected crime  
category and weeks as the time interval.  
```{r, echo=FALSE}
trainraw <- read.csv("../Data/sfcrime.csv")

Installed <- require("plyr")
if (!Installed) {
    install.packages("plyr")
    library("plyr")
}

Installed <- require("ggplot2")
if (!Installed) {
    install.packages("ggplot2")
    library("ggplot2")
}

Installed <- require("scales")
if (!Installed) {
    install.packages("scales")
    library("scales")
}

# Convert Dates variable from factor to date
trainraw$Date <- as.Date(trainraw$Date, format = "%m/%d/%Y")
# Count daily frequency of each crime
freqByCategory <- count(trainraw, c("Date", "Category"))

# Create data frame with only data from Category of ARSON
dataByArson <- freqByCategory[freqByCategory$Category == "ARSON", c(1, 3)]
# Extract month and year into new variables
dataByArson$Month <- as.Date(cut(dataByArson$Date, breaks = "month"))
dataByArson$Year <- as.Date(cut(dataByArson$Date, breaks = "year"))

plotByMonth <- ggplot(data = dataByArson, aes(Month, freq))
plotByMonth <- plotByMonth +
    stat_summary(fun.y = sum,  # adds up all observations for the month
                 geom = "line") +
    scale_x_date(labels = date_format("%m/%Y")) +  # custom x-axis labels
    ggtitle("Arson by Month") +
    labs(x = "Time", y = "Occurences per Month") +
    theme_bw()
print(plotByMonth)
```

--- .class #id 

## Conclusion

This app provides an easy way to visualize the historical data for a chosen  
crime. Future development of the app could include:

* Selection of intermediate time period (i.e. May 2015 - June 2015)
* Data filtered by police precinct or zip code
* Trend lines or other regression analyses

## Thank you


